export const ERROR_CODES = {
    //USUARIOS
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    EMAIL_EXISTS: 'EMAIL_EXISTS',
    NOT_AUTHORIZED: 'NOT_AUTHORIZED',
    USER_INACTIVE: 'USER_INACTIVE',

    //TAREAS
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
    TASK_ALREADY_ASSIGNED: 'TASK_ALREADY_ASSIGNED',
    TASK_NOT_ASSIGNED: 'TASK_NOT_ASSIGNED',
    INVALID_TRANSITION: 'INVALID_TRANSITION',

    //AUTH
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS'
};