###Crear un nuevo usuario
POST http://localhost:9090/api/users
Content-Type: application/json

{
    "name": "sergio",
    "email": "sergio@sergio.com",
    "password": "aaaaaaaa"
}

### Login de usuario Admin
POST http://localhost:9090/api/auth/login 
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "123456"
}


### Login de usuario normal
POST http://localhost:9090/api/auth/login 
Content-Type: application/json

{
    "email": "ssuper@visor.com",
    "password": "123456"
}


###Crear Tarea (ADMIN)
POST http://localhost:9090/api/tasks
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlODhmZjVjZC1mYzljLTQ3M2MtOTUxMC03MmE0MGVkNTJhYTgiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIl0sImlhdCI6MTc2ODMyMzIyNiwiZXhwIjoxNzY4MzM3NjI2fQ.e4OdTGxk4o0gEFI626x0AZlP5h9GMQfwkKWIKx2Uc_M

{
    "description": "Tarea para probar ruta takeee",
    "duration": 2,
    "difficulty": "XL"
}

### Obtener Tareas
GET http://localhost:9090/api/tasks
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlODhmZjVjZC1mYzljLTQ3M2MtOTUxMC03MmE0MGVkNTJhYTgiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIl0sImlhdCI6MTc2ODMyMzIyNiwiZXhwIjoxNzY4MzM3NjI2fQ.e4OdTGxk4o0gEFI626x0AZlP5h9GMQfwkKWIKx2Uc_M

### Asignar Tarea (ADMIN)
PATCH http://localhost:9090/api/tasks/696678c49cc53ddaad0013cf/assign
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlODhmZjVjZC1mYzljLTQ3M2MtOTUxMC03MmE0MGVkNTJhYTgiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIl0sImlhdCI6MTc2ODMyMzIyNiwiZXhwIjoxNzY4MzM3NjI2fQ.e4OdTGxk4o0gEFI626x0AZlP5h9GMQfwkKWIKx2Uc_M

{
    "userId": "696678809cc53ddaad0013cb"
}

### Cambiar estado de tarea a DOING  (debe permitir)
PATCH http://localhost:9090/api/tasks/696678c49cc53ddaad0013cf/status
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5Yjg3MGU2Zi05MTY1LTRhMzYtYmI2ZC05NDNhZjUzODIwMDIiLCJyb2xlcyI6WyJVU0VSX1JPTEUiXSwiaWF0IjoxNzY4MzI2NzE3LCJleHAiOjE3NjgzNDExMTd9.qqh_3_zwM-TcpIIJ4OxEq12TCOlubDu3hScLWHv5rb8
  

{
    "status":"doing"
}



### Cambiar estado de tarea a DOING con token no valido (debe fallar)
PATCH http://localhost:9090/api/tasks/69651f10c70debe569b07a88/status
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIdsfsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlODhmZjVjZC1mYzljLTQ3M2MtOTUxMC03MmE0MGVkNTJhYTgiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIl0sImlhdCI6MTc2ODMyMDY3NCwiZXhwIjoxNzY4MzM1MDc0fQ.D08YAnVhz7GffdFjgKzKkdRMbtADcwBHfSliLFL5GTo

{
    "status":"doing"
}


### Liberar tarea
PATCH http://localhost:9090/api/tasks/696678c49cc53ddaad0013cf/release
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5Yjg3MGU2Zi05MTY1LTRhMzYtYmI2ZC05NDNhZjUzODIwMDIiLCJyb2xlcyI6WyJVU0VSX1JPTEUiXSwiaWF0IjoxNzY4MzI3MDcyLCJleHAiOjE3NjgzNDE0NzJ9.TLad11Z4njIQF5ludlSJkyTktjnupgyY0-rIVeDO19s


### Auto-asignar una tarea takeTask
PATCH http://localhost:9090/api/tasks/69668fcfc9552fa12b870ecc/take
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5Yjg3MGU2Zi05MTY1LTRhMzYtYmI2ZC05NDNhZjUzODIwMDIiLCJyb2xlcyI6WyJVU0VSX1JPTEUiXSwiaWF0IjoxNzY4MzI3MDcyLCJleHAiOjE3NjgzNDE0NzJ9.TLad11Z4njIQF5ludlSJkyTktjnupgyY0-rIVeDO19s



### Eliminar Tarea como Admin (debe funcionar)
DELETE http://localhost:9090/api/tasks/69668fcfc9552fa12b870ecc
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJlODhmZjVjZC1mYzljLTQ3M2MtOTUxMC03MmE0MGVkNTJhYTgiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIl0sImlhdCI6MTc2ODMzOTY2NiwiZXhwIjoxNzY4MzU0MDY2fQ.oLRKIPDSaMplsxu2f2Ygr0KFXnUeUSXW94ueJRDsDeE


### Eliminar Tarea como User (debe fallar)
DELETE http://localhost:9090/api/tasks/696678c49cc53ddaad0013cf
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI5Yjg3MGU2Zi05MTY1LTRhMzYtYmI2ZC05NDNhZjUzODIwMDIiLCJyb2xlcyI6WyJVU0VSX1JPTEUiXSwiaWF0IjoxNzY4MzM5NzU1LCJleHAiOjE3NjgzNTQxNTV9.VHab5Z6-Ound2SFF6fpRZM7ZtWF24ySQNCjKAlCbbGA

###Lanzar Seeder
POST http://localhost:9090/api/tasks/seed
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIyOTVkZDI1MC05YzhlLTQyOTAtYTYxMS0wZjVhNGYyMTUyZmEiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODM0MzkzNiwiZXhwIjoxNzY4MzU4MzM2fQ.ES-2fZbNuROTr27nN9cKpyyWmGHAfFNDYWfaxqRRe1I


### Editar una tarea - caso éxito - Admin
PUT http://localhost:9090/api/tasks/6966c991650f94246f7aae14
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiOGNlZWEwYy04MzhlLTRjYTQtOGU0YS04YzA5YTM3YjIwNjIiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODQxMTA0OSwiZXhwIjoxNzY4NTU1MDQ5fQ.w1D8vbny0LSPlLNKuiKOehcQG-IVDCNqO-yEYPvWP8c

{
    "description": "Intento de hackeo",
    "difficulty": "L"
}

@url = http://localhost:9090


### 1.1 Registro Normal (Debe funcionar y devolver Token)
# Prueba de fuego: Intentamos inyectar "ADMIN_ROLE".
# RESULTADO ESPERADO: Crea el usuario, PERO ignora el rol Admin y le pone USER_ROLE.
POST {{url}}/api/auth/register
Content-Type: application/json

{
  "name": "Pepe Hacker",
  "email": "pepe@hacker.com",
  "password": "password123",
  "roles": ["ADMIN_ROLE"]
}


### ------------------------------------------------------------------------
### GESTIÓN DE USUARIOS (Solo Admin)
### 
### ------------------------------------------------------------------------

### Crear Usuario Admin

POST {{url}}/api/users
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiOGNlZWEwYy04MzhlLTRjYTQtOGU0YS04YzA5YTM3YjIwNjIiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODQzMDYzMCwiZXhwIjoxNzY4NTc0NjMwfQ.CwBYLqXo5l-LjCrAUCV1SItWTCgTideL8WoB6m8VooQ

{
  "name": "Nuevo Supervisor 2 ",
  "email": "ssuper@visor.com",
  "password": "123456",
  "roles": ["ADMIN_ROLE", "USER_ROLE"]
}

### Listar Todos los Usuarios

GET {{url}}/api/users
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiOGNlZWEwYy04MzhlLTRjYTQtOGU0YS04YzA5YTM3YjIwNjIiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODQzMDYzMCwiZXhwIjoxNzY4NTc0NjMwfQ.CwBYLqXo5l-LjCrAUCV1SItWTCgTideL8WoB6m8VooQ

### Obtener Usuario por ID

GET {{url}}/api/users/69681cf47fecd8bbeef065ad
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiOGNlZWEwYy04MzhlLTRjYTQtOGU0YS04YzA5YTM3YjIwNjIiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODQzMDYzMCwiZXhwIjoxNzY4NTc0NjMwfQ.CwBYLqXo5l-LjCrAUCV1SItWTCgTideL8WoB6m8VooQ

### Actualizar Usuario

PUT {{url}}/api/users/6968209fd03ed47c6fe7f457
Content-Type: application/json
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiOGNlZWEwYy04MzhlLTRjYTQtOGU0YS04YzA5YTM3YjIwNjIiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODQzMDYzMCwiZXhwIjoxNzY4NTc0NjMwfQ.CwBYLqXo5l-LjCrAUCV1SItWTCgTideL8WoB6m8VooQ

{
  "name": "Supervisor2222222",
  "state": true,
  "roles": "USER_ROLE" 
}

### Eliminar Usuario (Soft Delete)
DELETE {{url}}/api/users/69681cf47fecd8bbeef065ad
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJiOGNlZWEwYy04MzhlLTRjYTQtOGU0YS04YzA5YTM3YjIwNjIiLCJyb2xlcyI6WyJBRE1JTl9ST0xFIiwiVVNFUl9ST0xFIl0sImlhdCI6MTc2ODQzMDYzMCwiZXhwIjoxNzY4NTc0NjMwfQ.CwBYLqXo5l-LjCrAUCV1SItWTCgTideL8WoB6m8VooQ

### ------------------------------------------------------------------------
### usuario normal intenta entrar
### 
### ------------------------------------------------------------------------

### intenta listar usuarios
# resultado no tiene permisos
GET {{url}}/api/users
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiJjYjQ4YTg5MS05OGM0LTQ4MDYtODNkNS1iZWYwNWMwZDk3NDMiLCJyb2xlcyI6WyJVU0VSX1JPTEUiXSwiaWF0IjoxNzY4NDMyMDI0LCJleHAiOjE3Njg1NzYwMjR9.af32l6w5A3xaej69SGFQBPaE_Em9tsG38o7lWTMEkpM