###Crear un nuevo usuario
POST http://localhost:9090/api/users
Content-Type: application/json

{
    "name": "Anakin",
    "email": "Anakin@darth.com",
    "password": "obipadme"
}

### Login de usuario
POST http://localhost:9090/api/auth/login 
Content-Type: application/json

{
    "email": "Anakin@darth.com",
    "password": "obipadme"
}